package frc.robot;

import edu.wpi.first.apriltag.AprilTagFieldLayout;
import edu.wpi.first.apriltag.AprilTagFields;
import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation3d;
import edu.wpi.first.math.geometry.Transform3d;
import edu.wpi.first.math.geometry.Translation3d;
import edu.wpi.first.math.numbers.N1;
import edu.wpi.first.math.numbers.N3;
//Imports for Network Tables Functions
import edu.wpi.first.networktables.BooleanArrayPublisher;
import edu.wpi.first.networktables.BooleanPublisher;
import edu.wpi.first.networktables.DoubleArrayPublisher;
import edu.wpi.first.networktables.DoublePublisher;
import edu.wpi.first.networktables.IntegerArrayPublisher;
import edu.wpi.first.networktables.NetworkTable;
import edu.wpi.first.networktables.NetworkTableInstance;

//Imports for photonVision Functions
import org.photonvision.PhotonCamera;
import org.photonvision.PhotonUtils;
import org.photonvision.targeting.PhotonPipelineResult;
import org.photonvision.targeting.PhotonTrackedTarget;
import org.photonvision.PhotonPoseEstimator;

import java.util.Optional;

import org.photonvision.EstimatedRobotPose;
import edu.wpi.first.math.Matrix;

public class precisionVision {

    public boolean turretTagVisible;
    public boolean aprilTagVisible;

    private PhotonCamera turretCamera;
    private PhotonCamera leftRearCamera;
    private PhotonCamera rightRearCamera;

    private NetworkTable visionTurretData;
    public BooleanPublisher isOurGoalDetectedDisplay;
    public BooleanPublisher turretGoodLockDisplay;
    public DoubleArrayPublisher turretAnglesToGoalDisplay;
    public DoubleArrayPublisher turretDistancesToGoalDisplay;

    public DoublePublisher turretAngleToGoalAvgDisplay;
    public DoublePublisher turretDistanceToGoalAvgDisplay;
    public DoubleArrayPublisher turretXGoalDisplay;
    private double[] turretXGoal;
    public DoubleArrayPublisher turretYGoalDisplay;
    private double[] turretYGoal;

    public boolean turretGoodLock;
    private double[] turretAnglesToGoal;
    private double[] turretDistancesTogoal;

    public double turretAngleToGoal;
    public double turretDistanceTogoal;

    private NetworkTable visionLocalizationData;
    private DoublePublisher fieldLocX;
    private DoublePublisher fieldLocY;
    private DoublePublisher fieldLocRot;

    private NetworkTable aprilTagList;
    public BooleanPublisher[] isTagDetectedDisplay;
    public final static int MAX_TAGS = 32;

    // These are the Network tables for the cam data generated by each camera
    // private NetworkTable turretCamData;
    // private NetworkTable leftRearCamData;
    // private NetworkTable rightrearCamData;

    public static final AprilTagFieldLayout kTagLayout = AprilTagFieldLayout
            .loadField(AprilTagFields.k2026RebuiltAndymark);
    //public static final Transform3d kSledToLeftRearCam = new Transform3d(new Translation3d(-0.33, 0.33, 0.177),
    //        new Rotation3d(0.36222, .36222, 2.355)); // 20.754 deg = 0.36222 radians
        public static final Transform3d kSledToLeftRearCam = new Transform3d(new Translation3d(-0.33, 0.33, 0.177),
            new Rotation3d(0, 0.262, 2.355)); // 20.754 deg = 0.36222 radians

    public static final Transform3d kSledToRightRearCam = new Transform3d(new Translation3d(-0.33, -0.33, 0.177),
            new Rotation3d(-0.36222, .36222, 2.355)); // 20.754 deg = 0.36222 radians

    public boolean isOurGoalDetected;
    private boolean weAreBlueAlliance;

    private PhotonPoseEstimator leftRearPoseEstimator;
    private PhotonPoseEstimator rightRearPoseEstimator;

    // parameters for tracking status of april tag detection
    boolean[] isTagDetected;

    public precisionVision() {
        // This is the default constructor
        // Initialize the network tables
        visionTurretData = NetworkTableInstance.getDefault().getTable("VisionTurretData");
        isOurGoalDetectedDisplay = visionTurretData.getBooleanTopic("Is OUR  Goal Detected?").publish();
        turretGoodLockDisplay = visionTurretData.getBooleanTopic("LOCKED ON TO GOAL").publish();
        turretAngleToGoalAvgDisplay = visionTurretData.getDoubleTopic("ANGLE TO Goal").publish();
        turretDistanceToGoalAvgDisplay = visionTurretData.getDoubleTopic("DISTANCE To Goal").publish();
        turretAnglesToGoalDisplay = visionTurretData.getDoubleArrayTopic("ANGLEs TO Goal").publish();
        turretDistancesToGoalDisplay = visionTurretData.getDoubleArrayTopic("DISTANCEsTo Goal").publish();
        turretXGoalDisplay = visionTurretData.getDoubleArrayTopic("xTrans To Goal").publish();
        turretYGoalDisplay = visionTurretData.getDoubleArrayTopic("yTrans To Goal").publish();
        turretXGoal = new double[3];
        turretYGoal = new double[3];

        //locatlization Tables
        visionLocalizationData = NetworkTableInstance.getDefault().getTable("LocalizationData");
        fieldLocX = visionLocalizationData.getDoubleTopic("fieldLocX").publish();
        fieldLocY = visionLocalizationData.getDoubleTopic("fieldLocY").publish();
        fieldLocRot = visionLocalizationData.getDoubleTopic("fieldLocRot").publish();


        aprilTagList = NetworkTableInstance.getDefault().getTable("AprilTagList");

        isTagDetectedDisplay = new BooleanPublisher[MAX_TAGS];
        for (int i = 0; i < MAX_TAGS; i++) {
            String tagPublisherName = "Tag" + String.format("%02d", i + 1) + "isSeen";
            isTagDetectedDisplay[i] = aprilTagList.getBooleanTopic(tagPublisherName).publish();
        }

        turretAnglesToGoal = new double[3];
        turretDistancesTogoal = new double[3];

        // createContainers for Analyzing Tags
        isTagDetected = new boolean[MAX_TAGS];

        // Connect to the cameras
        turretCamera = new PhotonCamera("TurretCamera");
        leftRearCamera = new PhotonCamera("LeftRearCamera");
        rightRearCamera = new PhotonCamera("RightRearCamera");

        // Construct things for localization
        leftRearPoseEstimator = new PhotonPoseEstimator(kTagLayout, kSledToLeftRearCam);
        rightRearPoseEstimator = new PhotonPoseEstimator(kTagLayout, kSledToRightRearCam);
        //private Matrix<N3, N1> curStdDevs;

    }

    public boolean periodicUpdate() {
        // Call this periodically to service cameras and update position estimates

        /// ************ THIS SECTION DEALS WITH THE TURRET ONLY ********************/
        // Initialize all tags to fase so that as we iterate through tags we can check
        /// which ones are true
        for (int i = 0; i < MAX_TAGS; i++) {
            isTagDetected[i] = false;
        }
        turretGoodLock = false;

        // determine check all of the tags
        var turretCAMResults = turretCamera.getAllUnreadResults();
        if (!turretCAMResults.isEmpty()) {
            var aTurretCAMResult = turretCAMResults.get(turretCAMResults.size() - 1);
            if (aTurretCAMResult.hasTargets()) {
                // At least one AprilTag was seen by the camera
                for (var target : aTurretCAMResult.getTargets()) {

                    switch (target.getFiducialId()) {
                        case 5: // This is the redGoalCenterLeftFace
                            if (target.poseAmbiguity < 0.2 && !weAreBlueAlliance) {
                                turretGoodLock = true;
                                double x = target.getBestCameraToTarget().getX();
                                double y = target.getBestCameraToTarget().getY();
                                double z = target.getBestCameraToTarget().getRotation().getZ() + 3.141593;

                                double alpha = Math.atan(y / x);
                                double d = Math.sqrt(x * x + y * y);

                                double beta = z - alpha;

                                double Xg = d * Math.cos(alpha) + 0.5931 * Math.cos(alpha + beta);
                                double Yg = d * Math.sin(alpha) + 0.5931 * Math.sin(alpha + beta);

                                double thetaG = Math.atan(Yg / Xg);
                                double distG = Math.sqrt(Xg * Xg + Yg * Yg);

                                turretDistancesTogoal[0] = distG;
                                turretAnglesToGoal[0] = thetaG;

                                turretXGoal[0] = Xg;
                                turretYGoal[0] = Yg;
                            }
                            break;
                        case 2: // This is the redGoalCenterRightFace
                            if (target.poseAmbiguity < 0.2 && !weAreBlueAlliance) {
                                turretGoodLock = true;
                                double x = target.getBestCameraToTarget().getX();
                                double y = target.getBestCameraToTarget().getY();
                                double z = target.getBestCameraToTarget().getRotation().getZ() + 3.141593;

                                double alpha = Math.atan(y / x);
                                double d = Math.sqrt(x * x + y * y);

                                double beta = z - alpha;

                                double Xg = d * Math.cos(alpha) + 0.5931 * Math.cos(alpha + beta);
                                double Yg = d * Math.sin(alpha) + 0.5931 * Math.sin(alpha + beta);

                                double thetaG = Math.atan(Yg / Xg);
                                double distG = Math.sqrt(Xg * Xg + Yg * Yg);

                                turretDistancesTogoal[2] = distG;
                                turretAnglesToGoal[2] = thetaG;

                                turretXGoal[2] = Xg;
                                turretYGoal[2] = Yg;
                            }
                            break;
                        case 10: // This is the redGoalCenterFrontFace
                            if (target.poseAmbiguity < 0.2 && !weAreBlueAlliance) {
                                turretGoodLock = true;
                                double x = target.getBestCameraToTarget().getX();
                                double y = target.getBestCameraToTarget().getY();
                                double z = target.getBestCameraToTarget().getRotation().getZ() + 3.141593;

                                double alpha = Math.atan(y / x);
                                double d = Math.sqrt(x * x + y * y);

                                double beta = z - alpha;

                                double Xg = d * Math.cos(alpha) + 0.5931 * Math.cos(alpha + beta);
                                double Yg = d * Math.sin(alpha) + 0.5931 * Math.sin(alpha + beta);

                                double thetaG = Math.atan(Yg / Xg);
                                double distG = Math.sqrt(Xg * Xg + Yg * Yg);

                                turretDistancesTogoal[1] = distG;
                                turretAnglesToGoal[1] = thetaG;

                                turretXGoal[1] = Xg;
                                turretYGoal[1] = Yg;
                            }

                        case 18:
                            if (target.poseAmbiguity < 0.2 && weAreBlueAlliance) {
                                turretGoodLock = true;
                                double x = target.getBestCameraToTarget().getX();
                                double y = target.getBestCameraToTarget().getY();
                                double z = target.getBestCameraToTarget().getRotation().getZ() + 3.141593;

                                double alpha = Math.atan(y / x);
                                double d = Math.sqrt(x * x + y * y);

                                double beta = z - alpha;

                                double Xg = d * Math.cos(alpha) + 0.5931 * Math.cos(alpha + beta);
                                double Yg = d * Math.sin(alpha) + 0.5931 * Math.sin(alpha + beta);

                                double thetaG = Math.atan(Yg / Xg);
                                double distG = Math.sqrt(Xg * Xg + Yg * Yg);

                                turretDistancesTogoal[2] = distG;
                                turretAnglesToGoal[2] = thetaG;

                                turretXGoal[2] = Xg;
                                turretYGoal[2] = Yg;
                            }

                            break;
                        case 21:
                            if (target.poseAmbiguity < 0.2 && weAreBlueAlliance) {
                                turretGoodLock = true;
                                double x = target.getBestCameraToTarget().getX();
                                double y = target.getBestCameraToTarget().getY();
                                double z = target.getBestCameraToTarget().getRotation().getZ() + 3.141593;

                                double alpha = Math.atan(y / x);
                                double d = Math.sqrt(x * x + y * y);

                                double beta = z - alpha;

                                double Xg = d * Math.cos(alpha) + 0.5931 * Math.cos(alpha + beta);
                                double Yg = d * Math.sin(alpha) + 0.5931 * Math.sin(alpha + beta);

                                double thetaG = Math.atan(Yg / Xg);
                                double distG = Math.sqrt(Xg * Xg + Yg * Yg);

                                turretDistancesTogoal[0] = distG;
                                turretAnglesToGoal[0] = thetaG;

                                turretXGoal[0] = Xg;
                                turretYGoal[0] = Yg;
                            }

                            break;

                        case 26:
                            if (target.poseAmbiguity < 0.2 && weAreBlueAlliance) {
                                turretGoodLock = true;
                                double x = target.getBestCameraToTarget().getX();
                                double y = target.getBestCameraToTarget().getY();
                                double z = target.getBestCameraToTarget().getRotation().getZ() + 3.141593;

                                double alpha = Math.atan(y / x);
                                double d = Math.sqrt(x * x + y * y);

                                double beta = z - alpha;

                                double Xg = d * Math.cos(alpha) + 0.5931 * Math.cos(alpha + beta);
                                double Yg = d * Math.sin(alpha) + 0.5931 * Math.sin(alpha + beta);

                                double thetaG = Math.atan(Yg / Xg);
                                double distG = Math.sqrt(Xg * Xg + Yg * Yg);

                                turretDistancesTogoal[1] = distG;
                                turretAnglesToGoal[1] = thetaG;

                                turretXGoal[1] = Xg;
                                turretYGoal[1] = Yg;
                            }

                            break;

                        default:

                    }// End of Switch

                    isTagDetected[target.getFiducialId() - 1] = true;

                } // End of iterating over targets

            } // End of check for has targets

        } // End of check for has results

        turretXGoalDisplay.set(turretXGoal);
        turretYGoalDisplay.set(turretYGoal);

        double[] anglesInDegs = { turretAnglesToGoal[0] * 180 / 3.14, turretAnglesToGoal[1] * 180 / 3.14,
                turretAnglesToGoal[2] * 180 / 3.14 };
        turretAnglesToGoalDisplay.set(anglesInDegs);
        turretDistancesToGoalDisplay.set(turretDistancesTogoal);

        // Print all of the tag statuses to network tables to be used by elastic
        for (int i = 0; i < MAX_TAGS; i++) {
            isTagDetectedDisplay[i].set(isTagDetected[i]);
        }

        // determine if ourGoalWasDetected
        int[] ourGoalTagList;
        int[] redGoalTagList = { 5, 10, 2 };
        int[] blueGoalTagList = { 21, 26, 18 };
        if (weAreBlueAlliance) {
            ourGoalTagList = blueGoalTagList;
        } else {
            ourGoalTagList = redGoalTagList;
        }
        boolean tempOurGoalDetected = false;
        for (int i = 0; i < 3; i++) {
            tempOurGoalDetected = tempOurGoalDetected || checkTagDetected(ourGoalTagList[i]);
        }
        isOurGoalDetected = tempOurGoalDetected;
        isOurGoalDetectedDisplay.set(isOurGoalDetected);
        turretGoodLockDisplay.set(turretGoodLock);

        // TODO: This method for calculating averages sucks and should be fixed
        double avgAngle = 0;
        double avgDist = 0;
        double goalTgtsSeen = 0;

        for (int i = 0; i < 3; i++) {
            if (checkTagDetected(ourGoalTagList[i])) {
                avgAngle = avgAngle + turretAnglesToGoal[i];
                avgDist = avgDist + turretDistancesTogoal[i];
                goalTgtsSeen++;
            }

        }
        avgAngle = avgAngle / goalTgtsSeen;
        avgDist = avgDist / goalTgtsSeen;

        turretAngleToGoalAvgDisplay.set(avgAngle);
        turretDistanceToGoalAvgDisplay.set(avgDist);

        turretDistanceTogoal = avgDist;
        turretAngleToGoal = avgAngle;

        // ************** THIS SECTION DEALS WITH LOCALIZATION ESTIMATES */
        // Fetch the best estimate of camera to field multi-tag
        Optional<EstimatedRobotPose> visionEst = Optional.empty();
        for (var result : leftRearCamera.getAllUnreadResults()) {
            visionEst = leftRearPoseEstimator.estimateCoprocMultiTagPose(result);
            if (visionEst.isEmpty()) {
                visionEst = leftRearPoseEstimator.estimateLowestAmbiguityPose(result);

            }else{
                fieldLocX.set(visionEst.get().estimatedPose.getX());
                fieldLocY.set(visionEst.get().estimatedPose.getY());
                fieldLocRot.set(visionEst.get().estimatedPose.getRotation().getZ()*180/3.14);

            }

            //updateEstimationStdDevs(visionEst, result.getTargets());

            //visionEst.ifPresent(
                   // est -> {
                        // Change our trust in the measurement based on the tags we can see
                        //var estStdDevs = getEstimationStdDevs();

                        //estConsumer.accept(est.estimatedPose.toPose2d(), est.timestampSeconds, estStdDevs);
        //            });
        }

        /*
;
        //fieldLocX.set(visionEst.get().estimatedPose.getRotation().);
        */
        // Translate the cameras

        // Combine them

        return true;
    }

    /********* External Functions */

    public void setWeAreBlueAliance(boolean areWeBlueAlliance) {
        weAreBlueAlliance = areWeBlueAlliance;
    }

    /********* Internal Helper Functions *******/
    private boolean checkTagDetected(int tag) {
        return isTagDetected[tag - 1];

    }

    ///// ******** Turret Getters ********/
    public double getTurretAngleToGoalDeg() {
        return turretAngleToGoal * 180 / 3.14159;

    }

    public double getTurretAngleToGoalRad() {

        return turretAngleToGoal;

    }

    public double getTurretDistanceToGoalMeters() {
        // Returns distance to target in radians
        return turretDistanceTogoal;
    }

    public double getTurretDistanceToGoalInches() {
        return turretDistanceTogoal;

    }

    @FunctionalInterface
    public static interface EstimateConsumer {
        public void accept(Pose2d pose, double timestamp, Matrix<N3, N1> estimationStdDevs);
    }

}
